### ISSUE TITLE
Tweet画面に送信する画像のプレビューを表示して欲しい

### ISSUE THREAD

**Issue by katabame** [Siketyan/Screenshotter#14]
送信したいウィンドウがきちんと収まっているか等の確認の為、ツイートボタンの下などに送信する画像のプレビューを表示して欲しいです。

**Comment by siketyan** [comment]
現在ClipTweet（ https://github.com/Siketyan/ClipTweet ）という新しいものを制作していますので、レガシとなるこちらでは機能追加はしない方向です。申し訳ありません。

**Comment by katabame** [comment]
承知しました👏🏻
